---

- name: Get secret definition from pvc
  k8s_exec:
    namespace: "{{ tower_backup_pvc_namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c "cat '{{ tower_backup_dir }}/secrets.yml'"
  register: secrets

- include_vars: "{{ secrets.stdout | from_yaml }}"

- name: Apply secret
  k8s:
    state: present
    namespace: "{{ meta.namespace | default('default') }}"
    apply: yes
    wait: yes
    template: "secrets.yml.j2"
