---

- name: Update Tower Restore status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      towerRestoreComplete: true
  when: tower_restore_complete is defined
