---
- name: Create the awx.ansible.com/v1alpha1.AWX
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', 'awx_cr_molecule.yml.j2') | from_yaml }}"
    wait: yes
    wait_timeout: 900
    wait_condition:
      type: Running
      reason: Successful
      status: "True"

- name: Obtain generated admin password
  k8s_info:
    namespace: '{{ namespace }}'
    kind: Secret
    name: example-awx-admin-password
  register: admin_pw_secret

- name: Launch Demo Job Template
  awx.awx.job_launch:
    name: Demo Job Template
    wait: yes
    validate_certs: no
    controller_host: localhost
    controller_username: admin
    controller_password: "{{ admin_pw_secret.resources[0].data.password | b64decode }}"
