---
postgres_initdb_args: '--auth-host=scram-sha-256'
postgres_host_auth_method: 'scram-sha-256'
ldap_cacert_ca_crt: ''
tower_projects_existing_claim: ''
manual_upgrade_msg: 'Manual Upgrade is required, please refer to the upgrade docs'
