---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: example-awx
  namespace: example-awx
spec:
  deployment_type: awx
  ingress_type: ingress
  web_resource_requirements:
    requests:
      cpu: 500m
      memory: 128M
  task_resource_requirements:
    requests:
      cpu: 500m
      memory: 128M
