---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: example-awx
  namespace: example-awx
spec:
  deployment_type: awx
  tower_ingress_type: ingress
  tower_task_privileged: false

  tower_admin_email: test@example.com

  tower_image: quay.io/ansible/awx:execution-environments

  tower_web_resource_requirements:
    requests:
      cpu: 500m
      memory: 128M

  tower_task_resource_requirements:
    requests:
      cpu: 500m
      memory: 128M

  tower_create_preload_data: true

  tower_memcached_image: memcached:alpine

  tower_redis_image: redis:latest

  tower_postgres_pass: awxpass
  tower_postgres_image: postgres:12
  tower_postgres_storage_class: ''
