---
- name: Check for specified PostgreSQL configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ tower_postgres_configuration_secret }}'
  register: _custom_pg_config_resources
  when: tower_postgres_configuration_secret | length
  no_log: true

- name: Check for default PostgreSQL configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ meta.name }}-postgres-configuration'
  register: _default_pg_config_resources
  no_log: true

- name: Set PostgreSQL configuration
  set_fact:
    _pg_config: '{{ _custom_pg_config_resources["resources"] | default([]) | length | ternary(_custom_pg_config_resources, _default_pg_config_resources) }}'
  no_log: true

- block:
    - name: Create Database configuration
      k8s:
        apply: true
        definition: "{{ lookup('template', 'tower_postgres_secret.yaml.j2') }}"

    - name: Read Database Configuration
      k8s_info:
        kind: Secret
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-postgres-configuration'
      register: _generated_pg_config_resources
  when: not _pg_config['resources'] | default([]) | length
  no_log: true

- name: Set PostgreSQL Configuration
  set_fact:
    pg_config: '{{ _generated_pg_config_resources["resources"] | default([]) | length | ternary(_generated_pg_config_resources, _pg_config) }}'
  no_log: true

- name: Create Database if no database is specified
  k8s:
    apply: true
    definition: "{{ lookup('template', 'tower_postgres.yaml.j2') }}"
  when:
    - pg_config['resources'][0]['data']['type'] | default('') | b64decode == 'managed'
  no_log: true

- name: Store Database Configuration
  set_fact:
    awx_postgres_user: "{{ pg_config['resources'][0]['data']['username'] | b64decode }}"
    awx_postgres_pass: "{{ pg_config['resources'][0]['data']['password'] | b64decode }}"
    awx_postgres_database: "{{ pg_config['resources'][0]['data']['database'] | b64decode }}"
    awx_postgres_port: "{{ pg_config['resources'][0]['data']['port'] | b64decode }}"
    awx_postgres_host: "{{ pg_config['resources'][0]['data']['host'] | b64decode }}"
  no_log: true

- name: Check for old PostgreSQL configuration secret
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ tower_old_postgres_configuration_secret }}'
  register: old_pg_config
  when: tower_old_postgres_configuration_secret | length
  ignore_errors: true
  no_log: true

- name: Migrate data from old Openshift instance
  import_tasks: migrate_data.yml
  when: old_pg_config['resources'][0]['data']['host'] is defined
  ignore_errors: true
