---
# Required: specify name of tower deployment to backup from
tower_name: ''

# Specify a pre-created PVC (name) to backup to
tower_backup_pvc: ''
tower_backup_pvc_namespace: "{{ meta.namespace }}"

# Size of backup PVC if created dynamically
tower_backup_size: ''

# Specify storage class to determine how to dynamically create PVC's with
tower_backup_storage_class: ''
