---
- block:
    - name: Define secrets name
      set_fact:
        _admin_password: '{{ tower_admin_password_secret | length | ternary(tower_admin_password_secret, meta.name + "-admin-password") }}'
        _secret_key: '{{ tower_secret_key_secret | length | ternary(tower_secret_key_secret, meta.name + "-secret-key") }}'
        # yamllint disable-line rule:line-length
        _postgres_configuration: '{{ tower_postgres_configuration_secret | length | ternary(tower_postgres_configuration_secret, meta.name + "-postgres-configuration") }}'  # noqa 204

    - name: Remove ownerReferences reference
      k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: '{{ item }}'
            namespace: '{{ meta.namespace }}'
            ownerReferences: null
      loop:
        - '{{ _admin_password }}'
        - '{{ _secret_key }}'
        - '{{ _postgres_configuration }}'

  when: not tower_garbage_collect_secrets | bool
