name: helm-release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Create Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-chart
        env:
          VERSION: ${{ github.ref_name }}

      # Reinventing the wheel if/until https://github.com/helm/chart-releaser-action/pull/96 is merged
      - name: Release Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-release
        env:
          VERSION: ${{ github.ref_name }}
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
